baseURL = "https://learn-anything.xyz/"
languageCode = "en-us"
title = "Nikita Voloboev"
theme = "minimal"
googleAnalytics = "UA-74470910-1"

[params]
    author = "Nikita Voloboev"
    description = "Loves [making](https://nikitavoloboev.xyz/projects/) and [sharing](https://wiki.nikitavoloboev.xyz/sharing/sharing.html) things. <br/>Building an [Open Source](https://github.com/learn-anything/learn-anything) Website to [Learn Anything](https://learn-anything.xyz/) with Interactive Maps."
    githubUsername = "nikitavoloboev"
    accent = "#E34E47"
    copyright = "Built with 💗 using [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal) theme"
    showBorder = true
    backgroundColor = ""
    font = "Quicksand" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "https://medium.com/@NikitaVoloboev"
    name = "Blog"
    weight = 4

[[menu.main]]
    url = "https://wiki.nikitavoloboev.xyz"
    name = "Wiki"
    weight = 5

[[menu.main]]
    url = "https://my.mindnode.com/myLVaRLKytoTYBLshxGzzb75MN9cyGHbQBgaVVPp#323.6,381.4,3"
    name = "My Mind"
    weight = 6

[[menu.main]]
    url = "https://github.com/nikitavoloboev/ama"
    name = "Ask"
    weight = 8

[[menu.main]]
    url = "https://stackoverflow.com/cv/nikitavoloboev"
    name = "CV"
    weight = 9

[[menu.main]]
    url = "http://patreon.com/nikitavoloboev"
    name = "♥"
    weight = 10

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/
[[menu.icon]]
    url = "https://github.com/nikitavoloboev/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/nikitavoloboev/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://open.spotify.com/user/nikitavoloboev"
    name = "spotify"
    weight = 3

[[menu.icon]]
    url = "https://www.instagram.com/nikitavoloboev/"
    name = "instagram"
    weight = 4

[[menu.icon]]
    url = "https://www.youtube.com/channel/UCEKqrUfr_FMKIO9XSJS4vDw"
    name = "youtube"
    weight = 5

[[menu.icon]]
    url = "https://www.twitch.tv/niikivi"
    name = "twitch"
    weight = 6

[[menu.icon]]
    url = "https://soundcloud.com/nikitavoloboev"
    name = "soundcloud"
    weight = 7

[[menu.icon]]
    url = "https://stackoverflow.com/users/3067664/nikita-voloboev?tab=profile"
    name = "stack-overflow"
    weight = 8

[[menu.icon]]
    url = "https://www.quora.com/profile/Nikita-Voloboev"
    name = "quora"
    weight = 9

[[menu.icon]]
    url = "https://www.reddit.com/user/nikivi/"
    name = "reddit-alien"
    weight = 10

[[menu.icon]]
    url = "mailto:nikita.voloboev@icloud.com"
    name = "envelope-o"
    weight = 11